# tools/analyze_errors.py
# -*- coding: utf-8 -*-
"""
误判分析脚本
功能：
1. 读取 train_cnn_gru_att.py 生成的 test_preds.csv (包含预测值)
2. 读取 原始测试集 CSV (包含具体的攻击类型字符串，如 'DrDoS_DNS')
3. 合并两者，统计每种具体攻击类型的：样本数、误判数、准确率/召回率
4. 导出详细的错误分布表
"""

import pandas as pd
import argparse
import os
import sys
import yaml


def main():
    parser = argparse.ArgumentParser(description="Analyze misclassifications by attack type")
    parser.add_argument("--pred_file", type=str, required=True,
                        help="Path to test_preds.csv generated by training script")
    parser.add_argument("--config", type=str, default="config/cnn_gru_att.yaml",
                        help="Path to config file (to find original test dataset path)")
    parser.add_argument("--test_file", type=str, default=None,
                        help="Optional: Manual path to test.csv if not using config")

    args = parser.parse_args()

    # 1. 检查预测文件
    if not os.path.exists(args.pred_file):
        print(f"❌ Error: Prediction file not found: {args.pred_file}")
        return

    print(f"📖 Loading predictions from: {args.pred_file}")
    df_pred = pd.read_csv(args.pred_file)
    # df_pred columns: [y_true, y_prob, y_pred]

    # 2. 确定原始测试集路径
    test_path = args.test_file
    if test_path is None:
        if os.path.exists(args.config):
            with open(args.config, 'r', encoding='utf-8') as f:
                cfg = yaml.safe_load(f)
            test_path = cfg.get('data', {}).get('test_path')
        else:
            print(f"❌ Error: Config file not found: {args.config}")
            return

    if not test_path or not os.path.exists(test_path):
        print(f"❌ Error: Test dataset path invalid: {test_path}")
        return

    print(f"📖 Loading original test data from: {test_path}")

    # 我们只需要 label (字符串攻击名) 和 label_int (真值)
    # usecols 稍微优化内存
    try:
        df_orig = pd.read_csv(test_path, usecols=['label', 'label_int'])
    except ValueError:
        # 如果列名不对，尝试读取所有
        df_orig = pd.read_csv(test_path)
        if 'label' not in df_orig.columns:
            print("❌ Error: 'label' column (string) not found in test csv.")
            return

    # 3. 完整性检查与合并
    if len(df_pred) != len(df_orig):
        print(f"⚠️ Warning: Length mismatch! Preds: {len(df_pred)}, Orig: {len(df_orig)}")
        print("   这可能是由于 DataLoader 的 drop_last 设置或文件版本不一致导致的。")
        print("   将尝试取交集部分进行分析...")
        min_len = min(len(df_pred), len(df_orig))
        df_pred = df_pred.iloc[:min_len]
        df_orig = df_orig.iloc[:min_len]

    # 合并 DataFrame (按索引对齐)
    # 重置索引以确保安全
    df_merged = pd.concat([
        df_orig[['label']].reset_index(drop=True),
        df_pred.reset_index(drop=True)
    ], axis=1)

    # 4. 核心分析
    # 错误定义: y_true != y_pred
    df_merged['is_error'] = df_merged['y_true'] != df_merged['y_pred']

    # 区分 假阳性 (FP) 和 假阴性 (FN)
    # FP: True=0, Pred=1 (Benign -> Attack)
    # FN: True=1, Pred=0 (Attack -> Benign)
    df_merged['FP'] = (df_merged['y_true'] == 0) & (df_merged['y_pred'] == 1)
    df_merged['FN'] = (df_merged['y_true'] == 1) & (df_merged['y_pred'] == 0)

    # 按 'label' 分组统计
    stats = df_merged.groupby('label').agg(
        Total=('label', 'count'),
        Errors=('is_error', 'sum'),
        FP_Count=('FP', 'sum'),
        FN_Count=('FN', 'sum'),
        # 计算该类别的平均预测概率 (查看模型对该类的平均置信度)
        Avg_Prob=('y_prob', 'mean')
    ).reset_index()

    # 计算 错误率 (Error Rate) 和 召回率 (Recall)
    # 注意：对于 Benign，Recall 其实是 TNR (True Negative Rate)
    # 对于 Attack，Recall = 1 - (FN / Total)
    stats['Error_Rate'] = stats['Errors'] / stats['Total']
    stats['Accuracy'] = 1.0 - stats['Error_Rate']

    # 排序：按错误率从高到低，关注“最难啃的骨头”
    stats = stats.sort_values(by='Error_Rate', ascending=False)

    # 5. 输出报告
    print("\n" + "=" * 60)
    print(f"{'Attack Type':<20} | {'Total':<6} | {'Errors':<6} | {'Acc/Recall':<10} | {'Avg Prob':<8}")
    print("-" * 60)

    for _, row in stats.iterrows():
        name = str(row['label'])
        total = int(row['Total'])
        err = int(row['Errors'])
        acc = row['Accuracy']
        prob = row['Avg_Prob']

        # 高亮显示错误率高的
        marker = "🔴" if acc < 0.99 else "  "
        if acc < 0.90: marker = "❌"

        print(f"{marker} {name:<18} | {total:<6} | {err:<6} | {acc:.2%}{'':<4} | {prob:.4f}")

    print("=" * 60)

    # 保存结果
    out_dir = os.path.dirname(args.pred_file)
    save_path = os.path.join(out_dir, "error_analysis_by_type.csv")
    stats.to_csv(save_path, index=False)
    print(f"\n✅ Detailed analysis saved to: {save_path}")

    # 6. 额外提示：全局 FP/FN
    total_fp = df_merged['FP'].sum()
    total_fn = df_merged['FN'].sum()
    print(f"\nGlobal Summary:")
    print(f" - False Positives (误报): {total_fp} (Benign 判为 Attack)")
    print(f" - False Negatives (漏报): {total_fn} (Attack 判为 Benign)")


if __name__ == "__main__":
    main()